package com.echoflow.chat;

import org.json.JSONObject;

/**
 * 事件簿条目。
 */
public class StoryEvent {
    public String id;
    public String cardId;
    public String title;
    public long date;
    public String description;
    public String notes;
    public String imagePath;
    public boolean autoGenerated;

    public JSONObject toJson() throws Exception {
        JSONObject o = new JSONObject();
        o.put("id", id);
        o.put("cardId", cardId == null ? "" : cardId);
        o.put("title", title == null ? "" : title);
        o.put("date", date);
        o.put("description", description == null ? "" : description);
        o.put("notes", notes == null ? "" : notes);
        o.put("image", imagePath == null ? "" : imagePath);
        o.put("auto", autoGenerated);
        return o;
    }

    public static StoryEvent fromJson(JSONObject o) {
        StoryEvent e = new StoryEvent();
        e.id = o.optString("id");
        e.cardId = o.optString("cardId", "");
        e.title = o.optString("title", "");
        e.date = o.optLong("date", 0);
        e.description = o.optString("description", "");
        e.notes = o.optString("notes", "");
        e.imagePath = o.optString("image", "");
        e.autoGenerated = o.optBoolean("auto", false);
        return e;
    }
}
